# This is a test of creating new image based on dhcp-structural-pipeline:new-mirtk
FROM biomedia/dhcp-structural-pipeline:new-mirtk
MAINTAINER Xuxinyi
# copy dhcp-pipeline.sh /usr/local/src/structural-pipeline/
copy scripts/ /usr/local/src/structural-pipeline/scripts/
# copy parameters/recon-neonatal-cortex.cfg /usr/local/src/structural-pipeline/parameters/recon-neonatal-cortex2.cfg

CMD ["echo","Image created"]
